import collections.abc

def all(string: str, values: collections.abc.Sequence[str], case: bool = ...) -> bool: ...
def any(string: str, values: collections.abc.Sequence[str], case: bool = ...) -> bool: ...
