import typing
from typing import overload

class UnconsumingIO:
    @overload
    def __init__(self, stream: str) -> None: ...
    @overload
    def __init__(self, stream: object) -> None: ...
    def flush(self) -> None: ...
    def read(self, size: typing.SupportsInt | typing.SupportsIndex = ...) -> str: ...
    def seek(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def write(self, arg0: str) -> None: ...
    @overload
    def write(self, arg0: bytes) -> None: ...
    @property
    def pos(self) -> int: ...
