from typing import overload

class UnconsumingIO:
    def __init__(self, stream: object) -> None: ...
    def read(self, size: object = ...) -> str: ...
    @overload
    def write(self, arg0: str) -> None: ...
    @overload
    def write(self, arg0: bytes) -> None: ...
