[build-system]
requires = [ "setuptools>=74.1", "pybind11",]
build-backend = "setuptools.build_meta"

[project]
name = "philh_myftp_biz"
version = "v2026.09.11"
requires-python = ">=3.12"
dynamic = [ "dependencies",]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
ignore = [ "F401", "E731", "E402", "E701", "E722", "F403",]

[tool.setuptools.package-data]
"*" = [ "*.pyd", "*.so", "*.pyi",]

[tool.setuptools.dynamic.dependencies]
file = [ "requirements.txt",]
