from __future__ import annotations
import typing
__all__: list[str] = ['Formatter', 'MutInt', 'VERBOSE']
class Formatter:
    def __init__(self) -> None:
        ...
    def format(self, arg0: typing.Any) -> str:
        ...
class MutInt:
    def __add__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> MutInt:
        ...
    def __bool__(self) -> bool:
        ...
    def __iadd__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> MutInt:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __isub__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> MutInt:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def __sub__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> MutInt:
        ...
    @property
    def value(self) -> int:
        ...
    @value.setter
    def value(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
class VERBOSE(MutInt):
    def __init__(self, parsed_lvalue: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def disable(self) -> None:
        ...
    def enable(self) -> None:
        ...
    def pause(self) -> None:
        ...
    def resume(self) -> None:
        ...
    @property
    def lvalue(self) -> int:
        ...
    @lvalue.setter
    def lvalue(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
