import typing

def clamp(x: typing.SupportsFloat | typing.SupportsIndex, MIN: typing.SupportsFloat | typing.SupportsIndex, MAX: typing.SupportsFloat | typing.SupportsIndex) -> float: ...
def digit(num: typing.SupportsInt | typing.SupportsIndex, i: typing.SupportsInt | typing.SupportsIndex) -> int: ...
def is_float(num: object) -> bool: ...
def is_int(num: object) -> bool: ...
def is_num(num: object) -> bool: ...
def is_prime(num: object) -> bool: ...
def nearest_multiple(x: typing.SupportsFloat | typing.SupportsIndex, multiple_of: typing.SupportsInt | typing.SupportsIndex) -> int: ...
def nlen(num: object) -> int: ...
