import typing

class Stopwatch:
    def __init__(self) -> None: ...
    def start(self) -> Stopwatch: ...
    def stop(self) -> Stopwatch: ...
    def __eq__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool: ...
    def __float__(self) -> float: ...
    def __ge__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool: ...
    def __gt__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool: ...
    def __int__(self) -> int: ...
    def __le__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool: ...
    def __lt__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> bool: ...
    @property
    def elapsed(self) -> float: ...
    @property
    def running(self) -> bool: ...

class TimeStamp:
    def __init__(self, stamp: typing.SupportsFloat | typing.SupportsIndex, tz: str = ...) -> None: ...
    def stamp(self, format: str = ...) -> object: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __float__(self) -> float: ...
    def __gt__(self, arg0: object) -> bool: ...
    def __int__(self) -> int: ...
    def __lt__(self, arg0: object) -> bool: ...
    @property
    def ISO(self) -> str: ...
    @property
    def centisecond(self) -> int: ...
    @property
    def day(self) -> int: ...
    @property
    def decisecond(self) -> int: ...
    @property
    def hour(self) -> int: ...
    @property
    def microsecond(self) -> int: ...
    @property
    def millisecond(self) -> int: ...
    @property
    def minute(self) -> int: ...
    @property
    def month(self) -> int: ...
    @property
    def second(self) -> int: ...
    @property
    def unix(self) -> float: ...
    @property
    def year(self) -> int: ...

class Timeout(Stopwatch):
    def __init__(self, timeout: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def check(self) -> None: ...
    @property
    def timed_out(self) -> bool: ...
