import collections.abc

class _SubProcess:
    def __init__(self, args: collections.abc.Sequence[str], cwd: str, hide: bool, wait: bool) -> None: ...
    def stop(self) -> None: ...
    def wait(self) -> int: ...
    @property
    def pid(self) -> int: ...
    @property
    def running(self) -> bool: ...
    @property
    def stderr(self) -> str: ...
    @property
    def stdout(self) -> str: ...
