from __future__ import annotations
import pathlib
import typing
__all__: list[str] = list()
class _Path:
    @staticmethod
    def _parse(arg0: typing.Any) -> str:
        ...
    def __init__(self, arg0: typing.Any) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    @property
    def _pure(self) -> pathlib.Path:
        ...
    @property
    def exists(self) -> bool:
        ...
    @property
    def ext(self) -> str:
        ...
    @property
    def is_dir(self) -> bool:
        ...
    @property
    def is_file(self) -> bool:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def path(self) -> str:
        ...
    @property
    def wpath(self) -> str:
        ...
