from .Path import Path

loc: _loc

class _Path:
    def __init__(self, arg0: object) -> None: ...
    @property
    def exists(self) -> bool: ...
    @property
    def ext(self) -> str: ...
    @property
    def is_dir(self) -> bool: ...
    @property
    def is_file(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def wpath(self) -> str: ...

class _loc:
    def __init__(self) -> None: ...
    @property
    def cache(self) -> Path: ...
    @property
    def script(self) -> Path: ...
    @property
    def temp(self) -> Path: ...
