import typing

class Device:
    def __init__(self) -> None: ...
    @property
    def Connected(self) -> bool: ...
    @property
    def Name(self) -> str: ...

class HardDrive(Device):
    FriendlyName: str
    Usage: str
    def __init__(self, Tower: str, Conn: str, ID: typing.SupportsInt | typing.SupportsIndex, SN: str) -> None: ...
    @staticmethod
    def search() -> list[HardDrive]: ...
    @property
    def Conn(self) -> str: ...
    @property
    def ID(self) -> int: ...
    @property
    def Index(self) -> int: ...
    @property
    def SN(self) -> str: ...
    @property
    def Tower(self) -> str: ...

class PCIeCard(Device):
    def __init__(self, Slot: typing.SupportsInt | typing.SupportsIndex, Lanes: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    @property
    def Lanes(self) -> int: ...
    @property
    def Slot(self) -> int: ...

class VirtualDisk(Device):
    Connected: bool
    def __init__(self, Name: str, Mount: str) -> None: ...
    def Repair(self) -> None: ...
    @property
    def Mount(self) -> str: ...
