import typing

class HardDrive:
    FriendlyName: str
    Usage: str
    def __init__(self, Tower: str, Conn: str, ID: typing.SupportsInt | typing.SupportsIndex, SN: str) -> None: ...
    @property
    def Conn(self) -> str: ...
    @property
    def Connected(self) -> bool: ...
    @property
    def ID(self) -> int: ...
    @property
    def Index(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @property
    def SN(self) -> str: ...
    @property
    def Tower(self) -> str: ...

class PCIeCard:
    def __init__(self, Slot: str, Lanes: typing.SupportsInt | typing.SupportsIndex, DeviceId: str) -> None: ...
    @property
    def Connected(self) -> bool: ...
    @property
    def DeviceId(self) -> str: ...
    @property
    def Lanes(self) -> int: ...
    @property
    def Name(self) -> str: ...
    @property
    def Slot(self) -> str: ...

class VirtualDisk:
    Connected: bool
    def __init__(self, Name: str, Mount: str) -> None: ...
    def Repair(self) -> None: ...
    @property
    def Mount(self) -> str: ...
    @property
    def Name(self) -> str: ...
