import collections.abc
import typing

IP: _IP

class FirewallException:
    def __init__(self, name: str) -> None: ...
    def delete(self) -> None: ...
    def set(self, port: typing.SupportsInt | typing.SupportsIndex, dir: str = ...) -> None: ...
    @property
    def exists(self) -> bool: ...

class URL:
    def __init__(self, url: str, params: collections.abc.Mapping[str, str] = ..., headers: collections.abc.Mapping[str, str] = ..., max_tries: typing.SupportsInt | typing.SupportsIndex = ..., max_age: typing.SupportsInt | typing.SupportsIndex = ..., timeout: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    def child(self, name: str, **kwargs) -> URL: ...
    def copy(self, **kwargs) -> URL: ...
    def download(self, path: str, force: bool = ...) -> None: ...
    def format(self, *args, **kwargs) -> URL: ...
    @property
    def addr(self) -> str: ...
    @property
    def exists(self) -> bool: ...
    @property
    def furl(self) -> str: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @property
    def json(self) -> object: ...
    @property
    def params(self) -> dict[str, str]: ...
    @property
    def size(self) -> int: ...
    @property
    def text(self) -> str: ...
    @property
    def timeout(self) -> int: ...
    @property
    def url(self) -> str: ...

class _IP:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def LAN(self) -> str: ...
    @property
    def WAN(self) -> str: ...
