import typing

class FirewallException:
    def __init__(self, name: str) -> None: ...
    def delete(self) -> None: ...
    def set(self, port: typing.SupportsInt | typing.SupportsIndex, dir: str = ...) -> None: ...
    @property
    def exists(self) -> bool: ...
