import typing

IP: _IP

class FirewallException:
    def __init__(self, name: str) -> None: ...
    def delete(self) -> None: ...
    def set(self, port: typing.SupportsInt | typing.SupportsIndex, dir: str = ...) -> None: ...
    @property
    def exists(self) -> bool: ...

class _IP:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def LAN(self) -> str: ...
    @property
    def WAN(self) -> str: ...
