name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 22:00 EST

jobs:

  scan-changes:
    
    runs-on: ubuntu-latest

    outputs:
      has_changes: ${{ steps.verify.outputs.has_changes }}
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref || github.repository_default_branch }}
          fetch-depth: 1

      - name: Check Last Commit Message
        id: verify
        run: |
          if [ "$(git log -1 --format="%s")" == "Apply automatic changes" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

  main:
    runs-on: ubuntu-latest
    needs: scan-changes
    if: needs.scan-changes.outputs.has_changes == 'true'
  
    permissions:
      contents: write

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref || github.repository_default_branch }}

      - name: Get Current Date
        id: date
        run: |
          export TZ='America/New_York'
          echo "ISO=$(date +'%Y.%m.%d')" >> $GITHUB_ENV 

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

      - name: Initialize Python Packages
        run: |
          pip install poetry toml
          poetry lock
          poetry install --no-root --no-interaction

      - name: Update version in pyproject.toml
        run: |
          python -c "
          from toml import load, dump
          with open('pyproject.toml', 'r') as f:
              data = load(f)
          data['project']['version'] = 'v${{ env.ISO }}'
          with open('pyproject.toml', 'w') as f:
              dump(data, f)
          "
    
      - name: Save Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply automatic changes

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.ISO }}
          name: ${{ env.ISO }}
          body: Automatic Nightly Build
          prerelease: false
          draft: false

      - name: Build package
        run: poetry build

      - name: Publish package to PyPI
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
